import re
from typing import Tuple


class DangerClassifier:
    """
    Smart context-aware regex classifier for detecting danger in scene descriptions.
    It checks for danger keywords, and ensures they aren't negated within a
    specific word window before classifying as dangerous.
    """

    def __init__(self, window_size: int = 5):
        self.window_size = window_size

        # Base danger keywords (singular and plural handled implicitly by regex boundaries)
        danger_words = [
            "hole", "puddle", "fire", "accident", "glass", "crash",
            "manhole", "cliff", "flood", "smoke", "weapon", "knife",
            "tree", "debris", "obstacle", "gun", "hazard", "stairs", "step"
        ]

        # Base negation words
        negation_words = [
            "no", "not", "without", "free", "clear", "safe", "none", "never", "zero"
        ]

        # Compile base patterns
        # We use \b to ensure we match whole words or roots
        self.danger_pattern = re.compile(
            rf"\b({'|'.join(danger_words)})s?\b",
            re.IGNORECASE
        )

        self.negation_pattern = re.compile(
            rf"\b({'|'.join(negation_words)})\b",
            re.IGNORECASE
        )

    def classify(self, text: str) -> Tuple[str, str]:
        """
        Classifies a given text as SAFE or DANGEROUS.

        Args:
            text: The caption generated by the VLM.

        Returns:
            Tuple containing (Classification Label, Reason/Matched Danger)
        """
        if not text:
            return "SAFE", "No description provided."

        text = text.lower()

        # Find all dangerous words
        danger_matches = list(self.danger_pattern.finditer(text))

        if not danger_matches:
            return "SAFE", "No danger keywords detected."

        # We need to tokenize to easily check word distances
        words = re.findall(r'\b\w+\b', text)

        # Check context for each detected danger
        dangers_found = []

        for match in danger_matches:
            danger_word = match.group(0)

            # Find the position of this danger word in the tokenized list
            try:
                # Find occurrences of the danger word
                indices = [i for i, w in enumerate(words) if danger_word in w]
                if not indices:
                    continue  # Should not happen given regex matched

                # We check context around the first occurrence of the danger word for simplicity,
                # or we could check around all occurrences.
                danger_idx = indices[0]

                # Look backwards `window_size` words
                start_idx = max(0, danger_idx - self.window_size)
                preceding_words = words[start_idx:danger_idx]

                # Check if any preceding word is a negation word
                is_negated = any(self.negation_pattern.match(w) for w in preceding_words)

                # Check for "clear of", "free of" special phrases that might span multiple words
                # For simplicity, if 'clear' or 'free' is in the window, it often acts as negation

                if not is_negated:
                    dangers_found.append(danger_word)

            except ValueError:
                continue

        if dangers_found:
            return "DANGEROUS", f"Detected danger: {', '.join(dangers_found)}"

        # All dangers were negated
        return "SAFE", "Danger keywords were negated by context."
